# Generated by Django 3.1.2 on 2020-11-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registeredDate', models.DateField()),
                ('available', models.BooleanField(default=False)),
                ('bestSeller', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='category.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
