# Generated by Django 3.1.2 on 2020-11-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='steel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
