# Generated by Django 3.1.2 on 2020-11-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201117_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='steel',
            field=models.CharField(blank=True, choices=[('1060', '1060'), ('1075', '1075'), ('1095', '1095'), ('9260', '9260'), ('damasco', 'damasco'), ('dobrado', 'dobrado')], max_length=100),
        ),
    ]
