# Generated by Django 3.1.2 on 2020-12-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('steel', models.CharField(blank=True, choices=[('1060', '1060'), ('1075', '1075'), ('1095', '1095'), ('9260', '9260'), ('damasco', 'damasco'), ('dobrado', 'dobrado')], max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart', to='category.category')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
